routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\RetainerController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\CaseStudyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', HomeController::class);
Route::resource('services', ServicesController::class);
Route::resource('retainer', RetainerController::class);
Route::resource('case-studies', CaseStudyController::class);
Route::resource('partner', PartnerController::class);
Route::resource('contact', ContactController::class);

resources/views/master/cta.blade.php
<section class="px-5 py-16 mt-16 bg-white md:px-0 md:py-20 md:mt-32">
    <div class="container max-w-6xl mx-auto">
        <div class="grid grid-cols-1 gap-3 md:grid-cols-2">
            <div>
                <div class="flex flex-col">
                    <p data-aos="fade-right" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1000"
                        data-aos-easing="ease-in-out"
                        class="text-[#0A162C] uppercase italic font-black max-w-2xl text-4xl text-center md:text-[50px] md:text-left">
                        Got a Project?
                    </p>
                    <div data-aos="fade-right" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1100"
                        data-aos-easing="ease-in-out" class="mt-10 space-y-3">
                        <p
                            class="text-[#0A162C]  max-w-2xl text-2xl font-normal text-center md:text-[25px] md:text-left">
                            What can we build for you?
                        </p>
                        <p
                            class="text-[#0A162C]  max-w-2xl text-2xl font-normal text-center md:text-[25px] md:text-left">
                            Lets discuss your project...
                        </p>
                    </div>
                    <div data-aos="fade-right" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1150"
                        data-aos-easing="ease-in-out" class="mt-20 space-y-3 md:mt-40">
                        <p
                            class="text-[#0A162C]  max-w-2xl text-2xl font-semibold text-center md:text-[22px] md:text-left">
                            Email
                        </p>
                        <p class="text-[#0A162C]  max-w-2xl text-2xl text-center md:text-[22px] md:text-left">
                            team@toat.agency
                        </p>
                    </div>
                    <div
                        class="flex justify-center md:justify-start text-4xl md:text-[35px] text-[#00D7C7] space-x-3 mt-10">
                        <a data-aos="fade-up" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1100"
                            data-aos-easing="ease-in-out" href="#"><i
                                class="fa-brands fa-linkedin hover:text-[#0A162C]"></i></a>
                        <a data-aos="fade-up" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1150"
                            data-aos-easing="ease-in-out" href="#"><i
                                class="fa-brands fa-square-instagram hover:text-[#0A162C]"></i></a>
                    </div>
                </div>
            </div>
            <div class="" data-aos="fade-up" data-aos-offset="200" data-aos-delay="20" data-aos-duration="1100"
                data-aos-easing="ease-in-out">

                <form method="POST" action="{{ route('contact.store') }}">
                    @csrf
                    <div class="space-y-5">
                        @if (Session::has('success'))
                            <div class="px-6 py-5 mb-3 text-base text-green-700 bg-green-100 rounded-lg" role="alert">
                                {{ Session::get('success') }}
                            </div>
                        @endif
                        <div>
                            <label for="name" class="block mb-2 text-base font-medium text-gray-900">Name <span
                                    class="text-red-500">*</span></label>
                            <input type="text" id="name" name="name"
                                class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                placeholder="Write your full name">
                        </div>
                        <div>
                            <label for="email" class="block mb-2 text-base font-medium text-gray-900">Email <span
                                    class="text-red-500">*</span></label>
                            <input type="email" id="email" name="email"
                                class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                placeholder="Write your email">
                        </div>
                        <div>
                            <label for="company" class="block mb-2 text-base font-medium text-gray-900">Company <span
                                    class="text-red-500">*</span></label>
                            <input type="text" id="company" name="company"
                                class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                placeholder="Write your name name">
                        </div>
                        <div>
                            <label for="project" class="block mb-2 text-base font-medium text-gray-900">Tell us about
                                your project <span class="text-red-500">*</span></label>

                            <textarea id="project" rows="10" name="project"
                                class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg"
                                placeholder="Write on how we can start your project"></textarea>
                        </div>
                        <div class="flex flex-col space-y-5 md:flex-row md:space-y-0 md:space-x-5">
                            <div class="flex-1">
                                <label for="budget" class="block mb-2 text-base font-medium text-gray-900">Budget
                                    <span class="text-red-500">*</span></label>
                                <input type="number" id="budget" name="budget"
                                    class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                    placeholder="Write initial budget">
                            </div>
                            <div class="flex-col flex-1 space-y-3">
                                <div>
                                    <label for="timescale" class="block mb-2 text-base font-medium text-gray-900">Start
                                        Date
                                        <span class="text-red-500">*</span></label>
                                    <input type="date" id="timescale" name="start_date"
                                        class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                        placeholder="Write your time scale">
                                </div>
                                <div>
                                    <label for="timescale" class="block mb-2 text-base font-medium text-gray-900">End
                                        Date
                                        <span class="text-red-500">*</span></label>
                                    <input type="date" id="timescale" name="end_date"
                                        class="block w-full p-5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-gray-300 rounded-lg "
                                        placeholder="Write your time scale">
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="flex items-center justify-start mt-16 space-x-5">
                        <img src="{{ url('assets/content/button-arrow.svg') }}" alt="" />
                        <button type="submit" class="text-[#0A162C] font-semibold text-lg">Submit Enquiry</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>

resources/views/master/footer.blade.php
<hr class="px-20">
<footer class="bg-white px-5 md:px-0 py-10 pt-24 text-[#14233F]">
    <div class="container max-w-6xl mx-auto">

        <div class="flex flex-col md:flex-row justify-between space-y-24 md:space-y-0">
            <img src="{{ url('assets/images/logo-green.png') }}" alt=""
                class="mx-auto w-2/4 md:mx-0 md:w-auto md:h-8">

            <div class="space-y-12">
                <p class="text-[20px] uppercase font-bold">Development</p>
                <div class="flex flex-col space-y-5 text-[18px]">
                    <a href="#" class="hover:text-[#00D7C7]">Laravel Development</a>
                    <a href="#" class="hover:text-[#00D7C7]">WordPress Development</a>
                    <a href="#" class="hover:text-[#00D7C7]">PHP Web Development</a>
                    <a href="#" class="hover:text-[#00D7C7]">Custom Development</a>
                    <a href="#" class="hover:text-[#00D7C7]">App Development</a>
                </div>
            </div>
            <div class="space-y-12">
                <p class="text-[20px] uppercase font-bold">Strategy & Design</p>
                <div class="flex flex-col space-y-5 text-[18px]">
                    <a href="#" class="hover:text-[#00D7C7]">Strategy</a>
                    <a href="#" class="hover:text-[#00D7C7]">Digital</a>
                    <a href="#" class="hover:text-[#00D7C7]">CX Design</a>
                    <a href="#" class="hover:text-[#00D7C7]">Strategy Workshops</a>
                </div>
            </div>
            <div class="space-y-12">
                <p class="text-[20px] uppercase font-bold">Resource</p>
                <div class="flex flex-col space-y-5 text-[18px]">
                    <a href="#" class="hover:text-[#00D7C7]">Build Your MVP</a>
                    <a href="#" class="hover:text-[#00D7C7]">Support Maintenance</a>
                    <a href="#" class="hover:text-[#00D7C7]">Retainers</a>
                    <a href="#" class="hover:text-[#00D7C7]">Insights</a>
                    <a href="#" class="hover:text-[#00D7C7]">Partners</a>
                </div>
            </div>
        </div>

    </div>
    <div class="container max-w-6xl mx-auto mt-20">
        <div class="flex flex-col md:flex-row space-y-5 md:space-y-0 md:space-x-12">
            <p>Copyright © 2023 TOAT. All Rights Reserved.</p>
            <a href="#" class="hover:text-[#00D7C7]">Privacy</a>
            <a href="#" class="hover:text-[#00D7C7]">Terms</a>
            <a href="#" class="hover:text-[#00D7C7]">Cookies</a>
        </div>
    </div>
</footer>

resources/views/master/navigation.blade.php
<nav class="fixed w-full z-50 top-0 left-0 px-5 md:px-0 bg-[#0a162c]">

    <div class="container flex flex-wrap items-center justify-between max-w-6xl py-8 mx-auto">
        <a href="{{ route('index') }}" class="nav-logo"><img src="{{ url('assets/images/logo.png') }}"
                alt="TOAT Agency Logo" /></a>

        <button id="menu-btn" class="block hamburger focus:outline-none">
            <span class="hamburger-top"></span>
            <span class="hamburger-middle"></span>
            <span class="hamburger-bottom"></span>
        </button>
        <div class="navbar relative left-[-110%]" id="navmenu">
            <div class="nav-items">
                <a href="{{ route('services.index') }}" data-text="01/ Services" data-service="services"><span
                        class="text-[#00D7C7] nav-item-number">01/</span>
                    Services</a>
                <a href="{{ route('retainer.index') }}" data-text="02/ Retainers" data-service="retainers"><span
                        class="text-[#00D7C7] nav-item-number">02/</span>
                    Retainers</a>
                <div class="flex items-start space-x-3">
                    <a href="{{ route('case-studies.index') }}" data-text="03/ Case
                Studies"
                        data-service="case-studies"><span class="text-[#00D7C7] nav-item-number">03/</span> Case
                        Studies</a>
                    <p class="text-[#00D7C7] nav-item-case text-2xl font-bold">x{{ count($total) }}</p>
                </div>

                <a href="{{ route('partner.index') }}" data-text="04/ Partners" data-service="retainers"><span
                        class="text-[#00D7C7] nav-item-number">04/</span>
                    Partners</a>
                <a href="{{ route('contact.index') }}" data-text="05/ Contact" data-service="partneres"><span
                        class="text-[#00D7C7] nav-item-number">05/</span>
                    Contact</a>
            </div>
            <div class="absolute right-0 items-center justify-center hidden h-screen md:flex">
                <div id="case-studies" class="hidden floating">
                    <img src="{{ url('assets/images/sample.png') }}" alt="">
                </div>
            </div>
        </div>
    </div>

</nav>

resources/views/master/white_navigation.blade.php
<nav class="fixed top-0 left-0 z-50 w-full px-5 bg-white md:px-0">

    <div class="container flex flex-wrap items-center justify-between max-w-6xl py-8 mx-auto">
        <a href="{{ route('index') }}" id="dark_logo" class="nav-logo"><img src="{{ url('assets/images/dark_logo.png') }}"
                alt="TOAT Agency Logo" /></a>
        <a href="{{ route('index') }}" id="white_logo" class="hidden nav-logo"><img
                src="{{ url('assets/images/logo.png') }}" alt="TOAT Agency Logo" /></a>

        <button id="menu-btn" class="block hamburger focus:outline-none">
            <span class="hamburger-top-dark"></span>
            <span class="hamburger-middle-dark"></span>
            <span class="hamburger-bottom-dark"></span>
        </button>
        <div class="navbar relative left-[-110%]" id="navmenu">
            <div class="nav-items">
                <a href="{{ route('services.index') }}" data-text="01/ Services" data-service="services"><span
                        class="text-[#00D7C7] nav-item-number">01/</span>
                    Services</a>
                <a href="{{ route('retainer.index') }}" data-text="02/ Retainers" data-service="retainers"><span
                        class="text-[#00D7C7] nav-item-number">02/</span>
                    Retainers</a>
                <div class="flex flex-row space-x-3">
                    <a href="{{ route('case-studies.index') }}" data-text="03/ Case
                Studies"
                        data-service="case-studies"><span class="text-[#00D7C7] nav-item-number">03/</span> Case
                        Studies </a>
                    <p class="text-[#00D7C7] nav-item-case text-2xl font-bold">x{{ count($total) }}</p>
                </div>

                <a href="{{ route('partner.index') }}" data-text="04/ Partners" data-service="retainers"><span
                        class="text-[#00D7C7] nav-item-number">04/</span>
                    Partners</a>
                <a href="{{ route('contact.index') }}" data-text="05/ Contact" data-service="partneres"><span
                        class="text-[#00D7C7] nav-item-number">05/</span>
                    Contact</a>
            </div>
            <div class="absolute right-0 items-center justify-center hidden h-screen md:flex">
                <div id="case-studies" class="hidden floating">
                    <img src="{{ url('assets/images/sample.png') }}" alt="">
                </div>
            </div>
        </div>
    </div>

</nav>